# Site settings
title: "Kruno's blog"
email: mail@krunoknego.com
description: "Blog about web development. Currently I like using Symfony2 and Doctrine ORM so most of my blog posts will be about them. I also enjoy using Javascript frameworks and tools such as Vagrant."
baseurl: ""
url: "http://krunoknego.com"
gitusername: KrunoKnego
twitterusername: KKnego

# Build settings
markdown: kramdown
permalink: pretty
