# Site settings
title: "KRUNO KNEGO"
email: mail@krunoknego.com
description: "Blog about web development. Currently I like using Symfony2 and Doctrine ORM so most of my blog posts will be about them. I also enjoy using Javascript frameworks and tools such as Vagrant."
baseurl: ""
url: "http://krunoknego.com"
gitusername: KrunoKnego
twitterusername: KKnego
username: Kruno Knego
info: "I'm a passionate web developer specialized in Symfony2 framework. Currently employed at <a href=\"http://www.locastic.com\">Locastic</a>"

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
permalink: pretty

paginate: 20

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml

