# Site settings
title: "KRUNO KNEGO"
email: kruno@krunoknego.com
description: "Software engineering blog about web & mobile development. "
baseurl: ""
url: "http://krunoknego.com"
gitusername: KrunoKnego
twitterusername: KKnego
username: Kruno Knego
info: "Passionate and ambitious software engineer. My favorite quote is: \"Someone once told me the definition of Hell: The last day you have on earth, the person you became will meet the person you could have become.\" - Anonymous"
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

markdown: maruku
permalink: pretty
paginate: 20
exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml

